import os, json, subprocess

dst = os.path.expanduser("~/Documents/GitHub/cs-roster")
os.chdir(dst)
os.makedirs("docs/guides", exist_ok=True)

def w(path, content):
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    open(path, "w").write(content)
    print(f"  wrote {path}")

w("backend/app/api/__init__.py", "def register_blueprints(app):\n    from .auth import auth_bp\n    from .health import health_bp\n    from .users import users_bp\n    from .schedule import schedule_bp\n    from .upload import upload_bp\n    app.register_blueprint(auth_bp)\n    app.register_blueprint(health_bp)\n    app.register_blueprint(users_bp)\n    app.register_blueprint(schedule_bp)\n    app.register_blueprint(upload_bp)\n")

w("backend/config.py", "import os\nbasedir = os.path.abspath(os.path.dirname(__file__))\n\ndef build_database_url():\n    url = os.environ.get('DATABASE_URL', '')\n    if url: return url\n    host = os.environ.get('DB_HOST', '')\n    user = os.environ.get('DB_USER', '')\n    password = os.environ.get('DB_PASSWORD', '')\n    port = os.environ.get('DB_PORT', '3306')\n    name = os.environ.get('DB_NAME', '')\n    if host and user and name and password:\n        return f'mysql+pymysql://{user}:{password}@{host}:{port}/{name}?charset=utf8mb4'\n    return f'sqlite:///{os.path.join(basedir, \"dev.db\")}'\n\n_db_url = build_database_url()\n\nclass Config:\n    SECRET_KEY = os.environ.get('SECRET_KEY', 'dev-secret-change-me')\n    JWT_SECRET_KEY = os.environ.get('JWT_SECRET_KEY', 'jwt-secret-change-me')\n    SQLALCHEMY_DATABASE_URI = _db_url\n    SQLALCHEMY_TRACK_MODIFICATIONS = False\n    JSON_AS_ASCII = False\n    UPLOAD_FOLDER = os.path.join(basedir, 'uploads')\n    SQLALCHEMY_ENGINE_OPTIONS = (\n        {'connect_args': {'check_same_thread': False}}\n        if 'sqlite' in _db_url\n        else {'pool_pre_ping': True, 'pool_recycle': 3600}\n    )\n")

w("backend/requirements.txt", "Flask==2.3.3\nFlask-SQLAlchemy==3.1.1\nFlask-Migrate==4.0.5\nFlask-CORS==4.0.0\nmarshmallow==3.20.1\nPyJWT==2.8.0\nWerkzeug==2.3.7\npymysql==1.1.0\ncryptography==41.0.4\ngunicorn==21.2.0\nopenpyxl==3.1.2\n")

w("backend/schema.sql", "CREATE TABLE t_users (\n  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n  col_email VARCHAR(100) NOT NULL DEFAULT '',\n  col_password_hash VARCHAR(256) NOT NULL DEFAULT '',\n  col_name VARCHAR(50) NOT NULL DEFAULT '',\n  col_is_active TINYINT(1) NOT NULL DEFAULT 1,\n  col_can_edit_scheduler TINYINT(1) NOT NULL DEFAULT 0,\n  col_created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  PRIMARY KEY (id), UNIQUE KEY uniq_email (col_email)\n);\nCREATE TABLE t_schedule_state (\n  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n  col_key VARCHAR(50) NOT NULL DEFAULT 'current',\n  col_data LONGTEXT NOT NULL,\n  col_updated_by VARCHAR(100) NOT NULL DEFAULT '',\n  col_updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  PRIMARY KEY (id), UNIQUE KEY uniq_key (col_key)\n);\n")

w("backend/seed_demo.py", "from app import create_app\nfrom app.extensions import db\nfrom app.models.user import User\napp = create_app()\nwith app.app_context():\n    db.create_all()\n    for u in [\n        {'email':'admin@example.com','name':'Admin','password':'demo123456','can_edit_scheduler':1},\n        {'email':'viewer@example.com','name':'Viewer','password':'demo123456','can_edit_scheduler':0},\n    ]:\n        if not User.query.filter_by(email=u['email']).first():\n            user = User(email=u['email'],name=u['name'],is_active=1,can_edit_scheduler=u['can_edit_scheduler'])\n            user.set_password(u['password'])\n            db.session.add(user)\n    db.session.commit()\n    print('[seed] Done.')\n")

w("backend/.env.example", "# DB_HOST=127.0.0.1\n# DB_USER=root\n# DB_NAME=cs_roster\n# DB_PASSWORD=your_password\n# SECRET_KEY=change-me\n# JWT_SECRET_KEY=change-me\n")

w("frontend/package.json", json.dumps({"name":"cs-roster","version":"1.0.0","private":True,"type":"module","scripts":{"dev":"vite","build":"vite build","preview":"vite preview"},"dependencies":{"axios":"^1.6.0","element-plus":"^2.4.0","pinia":"^2.1.0","vue":"^3.4.0","vue-router":"^4.2.0"},"devDependencies":{"@types/node":">=18","@vitejs/plugin-vue":"^5.0.0","typescript":"^5.0.0","unplugin-auto-import":">=0.17.0","unplugin-vue-components":">=0.26.0","vite":"^5.0.0","vue-tsc":"^2.0.0"}}, indent=2)+"\n")

w("frontend/src/router/index.ts", "import { createRouter, createWebHistory } from 'vue-router'\nimport type { RouteRecordRaw } from 'vue-router'\nimport { getToken } from '@/utils/auth'\nconst routes: RouteRecordRaw[] = [\n  { path: '/login', name: 'Login', component: () => import('@/views/Login/index.vue'), meta: { title: 'Login', public: true } },\n  { path: '/', component: () => import('@/views/Layout/index.vue'), redirect: '/scheduler', children: [\n    { path: '/scheduler', name: 'Scheduler', component: () => import('@/views/Scheduler/index.vue'), meta: { title: 'Shift Scheduler' } },\n    { path: '/users', name: 'Users', component: () => import('@/views/Users/index.vue'), meta: { title: 'User Management' } },\n    { path: '/home', name: 'Home', component: () => import('@/views/Home/index.vue'), meta: { title: 'Home' } }\n  ]}\n]\nconst router = createRouter({ history: createWebHistory(), routes })\nrouter.beforeEach((to, _from, next) => {\n  if (to.meta.public) { next(); return }\n  if (!getToken()) { next({ path: '/login', query: { redirect: to.fullPath } }); return }\n  next()\n})\nexport default router\n")

w("frontend/src/views/Layout/index.vue", '<template>\n  <el-container class="layout-container">\n    <el-aside width="220px">\n      <div class="logo">CS Roster</div>\n      <el-menu :default-active="route.path" router background-color="#304156" text-color="#bfcbd9" active-text-color="#409eff">\n        <el-menu-item index="/scheduler"><el-icon><Calendar /></el-icon><span>Shift Scheduler</span></el-menu-item>\n        <el-menu-item index="/users"><el-icon><User /></el-icon><span>User Management</span></el-menu-item>\n      </el-menu>\n    </el-aside>\n    <el-container>\n      <el-header class="layout-header">\n        <span class="page-title">{{ route.meta.title }}</span>\n        <div class="header-right">\n          <span class="user-name">{{ userName }}</span>\n          <el-button type="danger" text @click="handleLogout">Logout</el-button>\n        </div>\n      </el-header>\n      <el-main><router-view /></el-main>\n    </el-container>\n  </el-container>\n</template>\n<script setup lang="ts">\nimport { ref, onMounted } from \'vue\'\nimport { useRoute, useRouter } from \'vue-router\'\nimport { User, Calendar } from \'@element-plus/icons-vue\'\nimport { getUserInfo } from \'@/api/auth\'\nimport { removeToken } from \'@/utils/auth\'\nconst route = useRoute()\nconst router = useRouter()\nconst userName = ref(\'\')\nonMounted(async () => { try { const u = await getUserInfo(); userName.value = u.name || u.email } catch {} })\nconst handleLogout = () => { removeToken(); router.push(\'/login\') }\n</script>\n<style scoped>\n.layout-container{height:100vh}.logo{height:60px;line-height:60px;text-align:center;font-size:18px;font-weight:bold;color:#fff;background:#263445}.el-aside{background:#304156}.layout-header{display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #e6e6e6;background:#fff}.page-title{font-size:16px;font-weight:500}.header-right{display:flex;align-items:center;gap:12px}.user-name{font-size:14px;color:#606266}\n</style>\n')

w("supervisord.conf", "[supervisord]\nnodaemon=true\nlogfile=/dev/null\nlogfile_maxbytes=0\n[program:nginx]\ncommand=nginx -g \"daemon off;\"\nautostart=true\nautorestart=true\nstdout_logfile=/dev/stdout\nstdout_logfile_maxbytes=0\n[program:init]\ncommand=bash -c \"cd /app/backend && flask db upgrade 2>/dev/null; python seed_demo.py || true\"\ndirectory=/app/backend\nautostart=true\nautorestart=false\nstartsecs=0\npriority=10\n[program:gunicorn]\ncommand=bash -c \"sleep 5; exec gunicorn --bind 127.0.0.1:5000 --workers 2 --timeout 120 run:app\"\ndirectory=/app/backend\nautostart=true\nautorestart=true\npriority=20\nstdout_logfile=/dev/stdout\nstdout_logfile_maxbytes=0\n")

w("docker-compose.yml", "services:\n  app:\n    build: .\n    ports: [\"8000:8000\"]\n    environment: [SECRET_KEY=demo-secret-key, JWT_SECRET_KEY=demo-jwt-secret]\n    volumes: [./backend/uploads:/app/backend/uploads]\n")

w("LICENSE", "MIT License\n\nCopyright (c) 2026 Isaac Cheng\n\nPermission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the \"Software\"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.\n")

w("README.md", "# CS Roster - Team Shift Scheduler\n\nInteractive shift scheduling tool replacing Excel-based roster management.\n\n## Quick Start\n\n```\ndocker-compose up --build\n```\n\nOpen http://localhost:8000 - login: admin@example.com / demo123456\n\n### Standalone Demo\n\nOpen `demo.html` in any browser - fully offline, data in localStorage.\n\n## Features\n\n- Monthly grid with drag-select and keyboard shortcuts\n- 13+ shift types with auto-calculated hours\n- Real-time validation\n- Overtime and comp-off tracking\n- Auto-scheduling algorithm\n- 50-step undo (Ctrl+Z)\n- Permission control\n- Export: TSV, Markdown, JSON\n\n## Tech Stack\n\nVue 3 + TypeScript + Element Plus | Flask 2.x + SQLAlchemy + JWT | SQLite/MySQL | Docker\n\n## Docs\n\n- [Lark Integration](docs/guides/lark-integration.md)\n- [Deployment](docs/guides/deployment.md)\n\n## License\n\nMIT\n")

w("docs/guides/deployment.md", "# Production Deployment\n\n## Docker with MySQL\n\n```\ndocker run -d --name cs-roster -p 8000:8000 \\\n  -e DB_HOST=host -e DB_USER=user -e DB_PASSWORD=pass -e DB_NAME=cs_roster \\\n  cs-roster:latest\n```\n\n## Health Checks\n\n- GET /health (liveness)\n- GET /api/health (readiness)\n")

w("docs/guides/lark-integration.md", "# Lark Bot Integration\n\n## Steps\n\n1. Create app at open.larksuite.com\n2. pip install lark-oapi\n3. Enable im.message.receive_v1 (WebSocket mode)\n\n## Example\n\n```python\nimport os, json, lark_oapi as lark\nfrom lark_oapi.api.im.v1 import *\nAPP_ID = os.environ['LARK_APP_ID']\nAPP_SECRET = os.environ['LARK_APP_SECRET']\ndef handle(data):\n    msg = data.event.message\n    print(json.loads(msg.content).get('text',''))\nhandler = lark.EventDispatcherHandler.builder('','').register_p2_im_message_receive_v1(handle).build()\nlark.ws.Client(APP_ID, APP_SECRET, event_handler=handler).start()\n```\n\n## Alternative Platforms\n\nSame pattern works for Slack, Discord, Microsoft Teams.\n")

# Git push
subprocess.run(["git", "add", "."], check=True)
subprocess.run(["git", "commit", "-m", "feat: add config, docs, demo, and missing frontend files"], check=True)
subprocess.run(["git", "push", "origin", "main"], check=True)
print("\nALL DONE - check https://github.com/isaaccwb/cs-roster")

