CREATE TABLE t_users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  col_email VARCHAR(100) NOT NULL DEFAULT '',
  col_password_hash VARCHAR(256) NOT NULL DEFAULT '',
  col_name VARCHAR(50) NOT NULL DEFAULT '',
  col_is_active TINYINT(1) NOT NULL DEFAULT 1,
  col_can_edit_scheduler TINYINT(1) NOT NULL DEFAULT 0,
  col_created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id), UNIQUE KEY uniq_email (col_email)
);
CREATE TABLE t_schedule_state (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  col_key VARCHAR(50) NOT NULL DEFAULT 'current',
  col_data LONGTEXT NOT NULL,
  col_updated_by VARCHAR(100) NOT NULL DEFAULT '',
  col_updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id), UNIQUE KEY uniq_key (col_key)
);
